config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :products do
    resources :comments
  end
  resources :users
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  root 'static_pages#index'

  post 'static_pages/thank_you'

  resources :orders, only: [:index, :show, :create, :destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
  <% if notice %>
  <p id="notice" class="alert alert-info"><%= notice %></p>
  <% end %>
    <% if alert %>
  <p id="alert" class="alert alert-info"><%= alert %></p>
  <% end %>
	<nav class="nav-collapse">
	  <ul>
	    <li><a><%= link_to "Home", static_pages_index_path %></a></li>
	    <li><a><%= link_to "About", static_pages_about_path %></a></li>
	    <li><a><%= link_to "Products", products_path %></a></li>
	    <li><a><%= link_to "Contact Us", static_pages_contact_path %></a></li>
      <form class="navbar-form" role="search">
        <div class="form-group">
        <%= form_tag("/products", method: "get") do %>
        <%= label_tag(:q, "Search for:") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
        <% end %>
        </div>
      </form>
	   </ul>
     <ul class="nav pull-right">
      <li>
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        <% else %>
          <%= link_to('Login', new_user_session_path) %>
        <% end %>
      </li>
     </ul>
	</nav>
  <%= yield %>
  <footer>
    <div class="twitter">
      <a href="https://twitter.com/summitwebdev" class="twitter-follow-button" data-size="large" data-show-count="false">Follow @summitwebdev</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div><!--end twitter-->
      <div class="fb-like" data-href="https://facebook.com/summit.webdev.1" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true">
      </div>
  	&nbsp&nbsp&copy; 2015 Bike Berlin
	</footer>
  </body>
</html>